export { default as UserLogin } from "../components/Authentication/Login/UserLogin";
export { default as UserRegistration } from "../components/Authentication/Registration/UserRegistration";
export { default as Sidebar } from "../components/Sidebar/Sidebar";
export { default as UserProfile } from "../components/Profile/UserProfile";
export { default as ManageTasks } from "./Tasks/ManageTasks/ManageTasks";
export { default as TaskForm } from "./Tasks/TaskForm/TaskForm";
export { default as TeamList } from "./Team/TeamList";
export { default as CreateTeam } from "./Team/CreateTeam/CreateTeam";
export { default as ManageTeam } from "./Team/ManageTeam/ManageTeam";